<?php
    // set bookid and pagex to link this php i.e. bookinfo.php?bookid=x&pagex=1
    session_start(); // start the session
    
     // ajax for editing the existing comments 
     if (isset($_POST["editcid"]) && isset($_POST["editcontent"]) && isset($_POST["editgrade"]))  { // if edit, commentid and content is set by edit button's jquery
        $editcid = $_POST["editcid"]; // get commentid from edit button's jquery
        $editcontent = $_POST["editcontent"];// get content from edit button's jquery
        $editgrade = $_POST["editgrade"];
        date_default_timezone_set("Asia/Hong_Kong"); // set the date("Y-m-d") & date("H:i:s") function return the correct difference of time
        $date = date("Y-m-d"); // get the current date YYYY-MM-DD
        $time = date("H:i:s"); // get the current time 00:00:00 - 23:59:59
        $conn = mysqli_connect("localhost", "root", "","mini4432"); // connect database, change username, pw & database name if needed
   		if ($conn->connect_error)  { // error of connection to database
			echo "Unable to connect to database"; // error message
		   	exit;
		}
   		$query = "UPDATE `Comment` SET Content = '".$editcontent."' WHERE CommentID ='" . $editcid . "'";   // update the Content in the table Comment 
    		$conn->query($query); // do the query
                $query = "UPDATE `Comment` SET Grade = '".$editgrade."' WHERE CommentID ='" . $editcid . "'";   // update the Grade in the table Comment 
    		$conn->query($query); // do the query
                $query = "UPDATE `Comment` SET Date = '".$date ."' WHERE CommentID ='" . $editcid . "'"; // update the Date in the table Comment
    		$conn->query($query); // do the query
                $query = "UPDATE `Comment` SET Time = '".$time ."' WHERE CommentID ='" . $editcid . "'"; // update the Time in the table Commen
    		$conn->query($query); // do the query
                echo json_encode(array( 'date'=>$date,'time'=>$time)); // encode the data return, 'date' for date & 'time' for time
                
        exit(); // exit not to run the HTML code below
    }
    
    // ajax for deleting existing comment
    if (isset($_POST["delcid"]))  { // if delete, CommentID is set by the delete button's jquery
        $delcid = $_POST["delcid"]; // get the CommentID from the delete button's jquery
        $conn = mysqli_connect("localhost", "root", "","mini4432"); // connect database, change username, pw & database name if needed
   		if ($conn->connect_error)  { // error of connection to database
			echo "Unable to connect to database"; // error message
		   	exit;
		}
   		$query = "DELETE FROM `BookComment` WHERE CommentID ='" . $delcid . "'";   // delete the comment record in table BookComment by CommentID(should be done before delete from Comment)
    		$conn->query($query);
                $query = "DELETE FROM `Comment` WHERE CommentID ='" . $delcid . "'"; // delete the comment record in table Comment by CommentID  
    		$conn->query($query);
                echo json_encode(array()); // return the empty encoded data, else error occur but status = 200
        exit(); // exit not to run the HTML code below
    }
    
    // ajax for adding a new comment
    if (isset($_POST['content']) && isset($_POST['grade'])){ //if add, content, bookid, grade are set by add button's jquery

        
        $content = $_POST['content']; // get content from add button jquery
        
        $grade = $_POST['grade']; // get grade from add button jquery
        date_default_timezone_set("Asia/Hong_Kong"); // set the date("Y-m-d") & date("H:i:s") function return the correct difference of time
        $date = date("Y-m-d"); // get the current date YYYY-MM-DD
        $time = date("H:i:s"); // get the current time 00:00:00 - 23:59:59
        $conn = mysqli_connect("localhost", "root", "","mini4432"); // connect database, change username, pw & database name if needed

   		if ($conn->connect_error)  { // error of connection to database
			echo "Unable to connect to database"; // error message
		   	exit;
		}

                
                // insert the CommentID, Content, Date, Grade, Time of new comment into table Comment (CommentID = NULL because of auto-increment)
   		$query = "INSERT INTO `Comment` (`CommentID`, `Content`, `Date`, `Grade`, `Time`) VALUES (NULL, '".$content."', '".$date."', '".$grade."', '". $time ."')";   
    		$conn->query($query); // do the query
                $query = "select max(CommentID) from Comment"; // calculate the maximum CommentID (previously generated by auto-increment)
    
    		$result = $conn->query($query); // do the query

    		while ($row = $result->fetch_assoc())  { // fetch the result
                    $commentid = $row['max(CommentID)']; // set the current commentid = auto set commentid
                }
                $result->free(); // free the memory
                // insert foreign key value of CommentID, BookID, NetID of new added comment into table BookComment
                $query = "INSERT INTO `BookComment` (`CommentID`, `BookID`, `NetID`) VALUES ('".$commentid."', '".$_SESSION['bookid']."', '".$_SESSION['netid']."')";   
    		$conn->query($query); // do the query

                echo json_encode(array( 'date'=>$date,'time'=>$time,'commentid'=>$commentid)); // encode the data return, 'date' for date & 'time' for time & 'commentid' for CommentID

        exit(); // exit not to run the HTML code below
    }
    
?>
<html>

<head> <title> Book Information </title> <!-- title -->

<script type="text/javascript" src="./js/commentoperation.js"></script> <!-- my javascript source-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> <!-- jquery source-->
<script>
    var arr = []; // array containing all the comment records
    var record = {}; // set containing all the comment variables 
    var cid = 0; // commentID, cid == 0 means that the comment record is deleted
    var nid = 0; // NetID
    var content = ""; // Content
    var grade = 0; // Grade
    var date = ""; //Date
    var time = ""; // Time
    var delenable = 0; // delenable == 0 => delete button not shown, 1=> shown when nid == $_SESSION['Netid']
    var editenable = 0; // editenable == 0 => edit button not shown, 1=> shown when nid == $_SESSION['Netid']
    $(document).ready(function(){
            
            // Edit button's onclick jquery function
            $(document).on("click",".edit",function(){ // define onclick function
            
            
            var $content = getcontent(); // get content by self-defined js function   
            var $grade = getgrade(); // get grade by self-defined js function
            var $editcid = $(this).data('editcid'); // get the CommentID edited by pass by the button's data (data-editcid)
            var $contentid = "content"+$(this).data('editcid'); // set the id of content in the cell of the table
            var $gradeid = "grade"+$(this).data('editcid'); // set the id of grade in the cell of the table
            var $dateid = "date"+$(this).data('editcid'); // set the id of date in the cell of the table
            var $timeid = "time"+$(this).data('editcid'); // set the id of time in the cell of the table
            var $url = "bookinfo.php?bookid="; // set the url in the format: e.g. "bookinfo.php?bookid=1&pagex=1"
                $url +=  <?php echo $_SESSION['bookid']; ?>;
             $url += "&pagex="+ <?php echo $_SESSION['pagex']; ?>;
             if ($content != "" && $grade != 0){
            $.ajax({ // jquery ajax function for editing
                type: "POST", // Post method
                url: $url, // set url
                dataType:"json", // set data typpe
                data: { editcid: $editcid, editcontent: $content, editgrade: $grade }, // two Post data passed into ajax function
                success: function(data) { // no error

                        document.getElementById($contentid).innerHTML = $content; // change the content in the cell of the table
                            switch ($grade) {
        case 1: // one star
            document.getElementById($gradeid).innerHTML = "★ ☆ ☆ ☆ ☆"; // change the grade in the cell of the table
            break;
        case 2: // two star
            document.getElementById($gradeid).innerHTML = "★ ★ ☆ ☆ ☆"; // change the grade in the cell of the table
            break;
        case 3: // three star
            document.getElementById($gradeid).innerHTML = "★ ★ ★ ☆ ☆"; // change the grade in the cell of the table
            break;
            
        case 4: // four star
            document.getElementById($gradeid).innerHTML = "★ ★ ★ ★ ☆"; // change the grade in the cell of the table
            break;
        case 5: // five star
            document.getElementById($gradeid).innerHTML = "★ ★ ★ ★ ★"; // change the grade in the cell of the table
            break;
    //cell4.innerHTML = grade;
    }
                        //document.getElementById($gradeid).innerHTML = $grade; // change the grade in the cell of the table
                        document.getElementById($dateid).innerHTML = data.date; // change the date in the cell of the table
                        document.getElementById($timeid).innerHTML = data.time; // change the time in the cell of the table
                        for ($i = 0; $i < arr.length; $i++){ // loop through all the record in arr
                            if (arr[$i].cid == $editcid){ // check which record is selected
                                //alert(arr[$i].cid); // show which commentid
                                
                                arr[$i].content = $content; // change the content in record
                                //alert(arr[$i].content); // show the changed content
                                arr[$i].grade = $grade;
                                //alert(arr[$i].grade); // show the changed grade
                                arr[$i].date = data.date; // change the date in record
                                arr[$i].time = data.time; // change the time in record
                            }
                        }
                        alert("Comment is edited successfully."); // success message
                },
                error: function(jqXHR) { // error

                alert("error: " + jqXHR.status); // error message
            }

            });
        }
        else {
            if ($content == "") // comment textarea is empty
                alert("Please enter your comment.");
            if ($grade == 0) // grade is not selected
                alert("Please grade the book.");
        }

        });
    
        // Delete jquery ajax function
        $(document).on("click",".del",function(){ // define Delete button onclick function
            
            
           
            var $delcid = $(this).data('delcid'); // get the CommentID edited by pass by the button's data (data-delcid)
            
            var $url = "bookinfo.php?bookid="; // set the url in the format: e.g. "bookinfo.php?bookid=1&pagex=1"
                $url +=  <?php echo $_SESSION['bookid']; ?>; // get bookid by session variable
             $url += "&pagex="+ <?php echo $_SESSION['pagex']; ?>; // get page number by session variable
             var $rowid = "row"+$delcid; // set the row id of removing comment record
            $.ajax({ // define jquery ajax function
                type: "POST", // POST method
                url: $url, // set url
                dataType:"json", // set dataType
                data: { delcid: $delcid }, // pass the commentid to the ajax function
                success: function() { // no error
                        for ($i = 0; $i < arr.length; $i++){ // loop through all the record in arr
                            if (arr[$i].cid == $delcid){ // check which record is selected
                                //alert(arr[$i].cid); // show commentid before change
                                arr[$i].cid = 0;
                                //alert(arr[$i].cid); // show commentid after change, arr[$i].cid will be = 0)
                            }
                        }
                        $('#'+$rowid).remove(); // remove the whole row of old comment record in the table
                        alert("Comment is deleted successfully."); // success message
                },
                error: function(jqXHR) { // error

                alert("error: " + jqXHR.status); // error message
            }

            });

        });
        
        // Add button's jquery ajax function
        $(document).on("click",".add",function(){ // define add button onclick function
            alert("Comment is added successfully.");
            
            var $content = getcontent(); // get content by self-defined js function
            //var $commentid = $(this).data('commentid');
            var $grade = getgrade(); // get grade by self-defined js function
            var $url = "bookinfo.php?bookid="; // set the url in the format: e.g. "bookinfo.php?bookid=1&pagex=1"
                $url +=  <?php echo $_SESSION['bookid']; ?>; // get the bookid by session variable
             $url += "&pagex=1"; // go back to page1 by setting pagex=1
             if ($content != "" && $grade != 0){
            $.ajax({ //  jquery ajax function
                type: "POST", // post method
                url: $url, // set url
                dataType:"json", // set data type
                data: { content: $content, grade: $grade}, // pass three data content, booid & grade to ajax function
                success: function(data) { // no error
                         // add a new row at the top of the table by self-defined js function addrow by passing 8 parameters
                        addrow(data.commentid, '<?php echo $_SESSION['netid']; ?>', $content, $grade, data.date, data.time);
                    cid = data.commentid; // store the commentid returned from ajax function
                    
                    nid = "<?php echo $_SESSION['netid'];?>"; // store the netid from session variable
                    content = $content; // store the content in textarea
                    grade = $grade; // store the grade selected
                    date = data.date; // store the date returned from ajax function
                    time = data.time; // store the time returned from ajax function
                    delenable = 1; // enable delete button
                    editenable = 1; // enable edit button
                    // store all the variables in record
                    record = {cid:cid, nid:nid, content:content, grade:grade, date:date, time:time, delenable:delenable, editenable:editenable}; 
                    arr.push(record); // push the record to the end of arr
                    // alert(arr[arr.length-1].cid); // show the commentid of the last record
                        alert("Comment is added successfully."); // success message
                },
                error: function(jqXHR) { // error

                alert("error: " + jqXHR.status); // error message
            }

            });
            }
            else {
                if ($content == "") // empty comment in textarea
                    alert("Please enter your comment.");
                if ($grade == 0) // grade is not selected
                    alert("Please grade the book.");            
            }
        });
        
    });
</script>
</head>

<body>
	   <?php
                
                if (isset($_GET['bookid'])){ // check if the url containing the data bookid
                    if (isset($_GET['pagex'])){ // check if the url containing the data pagex
                        $pagex = $_GET['pagex']; // set the php pagex variable
                        $_SESSION["pagex"] = $pagex; // set the pagex session variable
                    }
                    else { // pagex is not set in the url
                        $pagex = 1; // default pagex = 1
                        $_SESSION["pagex"] = 1; // default pagex = 1
                    }
                    $bookid = $_GET['bookid']; // store the get data bookid from url
                    $_SESSION['bookid'] =  $_GET['bookid']; // store in session variable bookid 
                    if (isset($_SESSION['netid'])){ // check if the use logged in
                        $netid = $_SESSION['netid']; // store the netid if logged in
                    }
      		$conn = mysqli_connect("localhost", "root", "","mini4432"); // connect database, change username, pw & database name if needed
   		if ($conn->connect_error)  { // connection error
			echo "Unable to connect to database"; // error message
		   	exit;
		}
		/*
                $query = "select * from Book where BookID='".$bookid."'"; // select all the information of a book by its bookid from the database
                $result = $conn->query($query); // do the query
                while ($row = $result->fetch_assoc()){ // while there is something to fetch
                    echo "<img src=".$row['Cover'].">"; // show the picture of the book
                    echo "<br>";
                    echo "BookID: " . $row['BookID']; // show the bookid
                    echo "<br>";
                    echo "Title: " . $row['Title']; // show the book title         
                    echo "<br>";
                    echo "Author: " . $row['Author']; // show the author
                    echo "<br>";
                    echo "Publisher: " . $row['Publisher']; // show the publisher
                    echo "<br>";
                    echo "ISBN: " . $row['ISBN']; // show the ISBN
                    echo "<br>";
                    echo "Call Number: "; // show the Call Number
                        if ($row['CallNumber'] == NULL) { // Call Number is NULL
                            echo "N/A"; // show Not Applicable
                        }
                        else { // Call Number is not NULL
                            echo $row['CallNumber']; // show Call Number
                        }
                    echo "<br>";
                    if ($row['CourseBook'] == 0){ // check if the book is a course book
                        echo "Course Book: No"; // show is not a course book
                        echo "<br>";
                    }
                    else {
                        echo "Course Book: Yes"; // show is a course book
                        echo "<br>";
                    }
                    echo "<br>";
                    echo "Comment"; // Show comment below
                    
                }*/
                $query = "select count(*) from BookComment where BookID='".$bookid."'"; // select the number of comments
                $result = $conn->query($query); // do the query
                while ($row = $result->fetch_assoc()){ // fetch the data
                    $numofcomment = $row['count(*)']; // store the number of comments
                    $maxpage = ceil($row['count(*)']/10); // store the maximun page avaliable  e.g. 23comments => 3 pages, maxpage = ceil(23/10)
                }
                // get the popularity by summing up all the grade for a book
                $query = "SELECT SUM(Grade) FROM Comment WHERE CommentID IN(SELECT CommentID From BookComment WHERE BookID='".$bookid."')"; 
                $result = $conn->query($query); // do the query
                while ($row = $result->fetch_assoc()){ // fetch data
                    $popularity = $row['SUM(Grade)']; // store the popularity
                }
                echo "(".$numofcomment.") Popularity: ". $popularity ."★"; // show the number of comments and the popularity
                //select all the information of a comment in the book by bookid sorted by the date and time descendingly
                $query2 = "select Content, Grade, Date, Time, Comment.CommentID, NetID from Comment, BookComment where BookID = ".$bookid." AND Comment.CommentID = BookComment.CommentID ORDER BY `Comment`.`Date` DESC, `Comment`.`Time` DESC";
                $result2 = $conn->query($query2); // do the query
                $pagecount = 10; // maximum number of comments shown is 10, add button is clicked then can shown more than 10
                $recordcount = 0; // count number of comments shown
                $count = 0; // counter where to start showing the comments, page1: 0 start, page2: 10 start, etc
                ?>
    
    <table id="commenttb" cellpadding=4 cellspacing=0 border=1 style="border-collapse: collapse" bordercolor="#AAAAAA">
         <tr> <!-- table header -->
             <th>Comment ID</th>
             <th>NetID</th>
             <th>Content</th>
             <th>Grade</th>
             <th>Date</th>
             <th>Time</th>
             <th>Delete</th>
             <th>Edit</th>
        </tr>
        <?php
			if($result2){
                while ($count < ($pagex-1)*$pagecount){ // fetch away unnessary data page1 shows 0-9 comments, page2 shows 10-19 comments
                    $row2 = $result2->fetch_assoc(); // fetch the data and do nothing
                    $count ++;
                }
                while (($row2 = $result2->fetch_assoc()) && $recordcount < $pagecount){ // fetch the data and shown in a form of table if there does not reach 10 records
                    $recordcount++;
			
        ?>
        <tr id="row<?php echo $row2['CommentID'];?>">
        <script> cid = <?php echo $row2['CommentID'];?>;</script> <!-- store the js var cid -->
            <td><?php echo $row2["CommentID"];?></td>
            <script> nid = '<?php echo $row2['NetID'];?>';</script> <!-- store the js var nid -->
            <td><?php echo $row2["NetID"];?></td>
            <script> content = '<?php echo $row2['Content'];?>';</script> <!-- store the js var content -->
            <td id="content<?php echo $row2['CommentID'];?>"><?php echo $row2["Content"]; ?></td> <!-- show content -->
            <td id="grade<?php echo $row2['CommentID'];?>"><?php //show grade
                                    switch ($row2['Grade']) {
                            case '1': // one star
                                echo "&#9733 &#9734 &#9734 &#9734 &#9734";?>
                               <script> grade = '<?php echo $row2['Grade'];?>';</script> <!-- store the js var grade -->
                                <?php
                                break;
                            case '2': // two star
                                echo "&#9733 &#9733 &#9734 &#9734 &#9734";?>
                               <script> grade = '<?php echo $row2['Grade'];?>';</script> <!-- store the js var grade -->
                                <?php
                                break;
                            
                            case '3': // three star
                                echo "&#9733 &#9733 &#9733 &#9734 &#9734";?>
                               <script> grade = '<?php echo $row2['Grade'];?>';</script> <!-- store the js var grade -->
                                <?php
                                break;
                            case '4': // four star
                                echo "&#9733 &#9733 &#9733 &#9733 &#9734";?>
                               <script> grade = '<?php echo $row2['Grade'];?>';</script> <!-- store the js var grade -->
                                <?php
                                break;
                            case '5': // five star
                                echo "&#9733 &#9733 &#9733 &#9733 &#9733";?>
                               <script> grade = '<?php echo $row2['Grade'];?>';</script> <!-- store the js var grade -->
                                <?php
                                
                                break;
                        }
            ?></td>
            <script> date = '<?php echo $row2['Date'];?>';</script> <!-- store the js var date -->
            <td id="date<?php echo $row2['CommentID'];?>"><?php echo $row2["Date"]; ?></td> <!-- show date -->
            <script> time = '<?php echo $row2['Time'];?>';</script> <!-- store the js var grade -->
            <td id="time<?php echo $row2['CommentID'];?>"><?php echo $row2["Time"]; ?></td> <!-- show time -->
            <script> delenable = 0;</script> <!-- initialize the js var delenable -->
            <td><?php if (isset($_SESSION['netid'])) if ($row2["NetID"] == $_SESSION['netid']) { // if it is the user's comment shown delete button
                echo "<button class='del' data-delcid ='". $row2['CommentID']."'>Delete</button>"; // show delete button ?> 
                <script> delenable = 1;</script> <!-- store the js var delenable -->
                <?php
            }?>
            </td>
            <script> editenable = 0;</script> <!-- initialize the js var editable -->
            <td><?php if (isset($_SESSION['netid'])) if ($row2["NetID"] == $_SESSION['netid']) { // if it is the user's comment shown edit button
                
                echo "<button class='edit' data-editcid ='". $row2['CommentID']."'>Edit</button>"; //show edit button ?>
                <script> editenable = 1;</script> <!-- store the js var editable -->
                <?php
            }?>
            </td>
        </tr>
        <script> 
            // store all the js variables it a record
            record = {cid:cid, nid:nid, content:content, grade:grade, date:date, time:time, delenable:delenable, editenable:editenable}; 
            arr.push(record); // push the record to the end of arr
 
        </script>
        <?php
                } 
			}				
        ?>
    </table>
    <script>//var arr2 = arr.slice(0,1); alert(arr2[0].cid);// extract the first record in arr and show its cid</script>
    <script>//var arr2 = arr.slice(1,2); alert(arr2[0].cid);// extract the second record in arr and show its cid</script>
    <br>
    <?php if ($_SESSION['pagex']>1) { echo "Previous page"; // enable the left arrow on click?>
    <a href=bookinfo.php?bookid=<?php echo $bookid;?>&pagex=<?php echo $_SESSION["pagex"]-1;?>> <img src=leftarrow.jpg border=0></a>
    <?php } ?>
    <?php if ($_SESSION['pagex'] < $maxpage) { // enable the right arrow onclick?>
    <a href=bookinfo.php?bookid=<?php echo $bookid;?>&pagex=<?php echo $_SESSION["pagex"]+1;?>> <img src=rightarrow.jpg border=0></a>
    <?php echo "Next page";} ?>
    
                <?php
                echo "<br>";
                echo "<br>";
    		echo "Page".$_SESSION['pagex']; // current page
                echo "/";
                echo "Page".$maxpage; // maximum page
                echo "<br>";
                $pagenum = 1;
                ?>
    <!--  drop box to select which page, current page's option is selected-->
    <select id = "page" onchange="window.document.location.href='bookinfo.php?bookid=<?php echo $bookid;?>&pagex='+this.options[this.selectedIndex].value;">
                    <?php while ($pagenum <= $maxpage) { // show up to maximum page?>
        <option value="<?php echo $pagenum;?>" <?php if($pagenum == $_SESSION['pagex']) echo "selected";?>>Page<?php echo $pagenum?></option>
                    <?php 
                    $pagenum++;
                    }?>
</select>
                <?php
                echo "<br>";
                echo "<br>";
                if (isset($_SESSION['netid'])){ // if logged in, can leave or edit comment
                
                echo "Add or edit your comment here:";
                
                ?>
                <br>
                <textarea id="comment" maxlength="45" placeholder="Enter your comment here."></textarea> <!-- place that enter comment-->
                <br>
                <span id="s1" onmouseover="onestar()">&#9734; </span> <!-- mouseover = one star -->
                <span id="s2" onmouseover="twostar()">&#9734; </span> <!-- mouseover = two star -->
                <span id="s3" onmouseover="threestar()">&#9734; </span> <!-- mouseover = three star -->
                <span id="s4" onmouseover="fourstar()">&#9734; </span> <!-- mouseover = four star -->
                <span id="s5" onmouseover="fivestar()">&#9734; </span> <!-- mouseover = five star -->
                <br>
                <br>
                <?php
                if($result2)
                echo "<button class='add' data-commentid ='". $row2['CommentID']."'>Add</button>"; // Show add button
                } else{
                echo "<button class='add' data-commentid ='0'>Add</button>"; // Show add button
					
				}
                //$result3->free();
				if($result2)
                $result2->free(); //  free the memory
               
                
   		$conn->close(); // close the connection of database
                }
                else {
                    header("Location: bookresult.php");  // if bookid is not set, redirect to the book selection page
                }
            ?>
            

</body>

</html>
